MOOC_blog/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :lectures do
    resources :comments
  end
  resources :courses do
    resources :lectures
  end
  get 'pages/index'

  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'comments/create'

  mount Ckeditor::Engine => '/ckeditor'
  

  devise_for :users, controllers: {sessions: 'users/sessions',registrations: "users/registrations"}

  resources :users
  resources :courses
  resources :comments, :only => [:create, :destroy]
  resources :lectures do
    member do
      put 'like' => 'lectures#upvote'
      put 'unlike' => 'lectures#downvote'
    end
  end
  
  get 'lectures/index'

  get 'lectures/show'

  get 'lectures/edit'

  get 'lectures/create'

  get 'lectures/destroy'

  get 'lectures/new'

  get 'lectures/update'

  get 'lectures/set_lecture'

  get 'lectures/lecture_params'

 

  get 'courses/index'
  get 'courses/new'
  get 'courses/create'
  get 'courses/show'
  get 'courses/update'
  get 'courses/create'
  get 'courses/create'
  
  

  root 'courses#index'

end

MOOC_blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :lecture
  belongs_to :user
end

MOOC_blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # if user not log in he can't use those actions
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :create, :new] 
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
   def index
      @comments = Comment.all
   end
   
   def new
      @comment = Comment.new
   end
   
   def create
      @user_id = current_user.id 
#    @lecture = Lecture.find(params[:lecture_id])
     @comment = Comment.new(comment_params)
      respond_to do |format|
         if @comment.save
            format.html {redirect_to controller:"lectures" , action: "show", id:params[:lecture_id]}
         else
            format.html {reder :new} 
         end
      end
   end
   
   def update
     respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment }
      else
        format.html { render :edit }
      end
    end
   end
   
   def edit
   end
   
   def show
   end
   
   def destroy
   end

  private
    def set_comment
      
       @comment = Comment.find(params[:id])
    end
    
    def comment_params
      params.require(:comment).permit(:user_id, :lecture_id, :comment_title, :body)
    end
end

MOOC_blog/app/helpers/comments_helper.rb
module CommentsHelper
end

MOOC_blog/app/views/comments/_comment.html.erb
<%= div_for(comment,class:"comment") do %>
<p>
    
    <%#*The h method is commonly used to escape HTML and Javascript from user-input forms.%>
    <strong style="font-size: 16px; color: darkcyan"><%= comment.comment_title %> </strong><br>
       <p style="font-size: 18px;"><%= comment.body %></p>
    <strong>Posted <%= time_ago_in_words(comment.created_at) %> ago</strong><br>
    <%=link_to "Edit comment", edit_comment_path(comment.id) %>
</p>
<% end %>

MOOC_blog/app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>

  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :user_id %>
  </div>
  <div class="field">
    <%= f.hidden_field :lecture_id %>
  </div>
    
  <div class="field">
    <%= f.label :comment_title %><br>
    <%= f.text_field :comment_title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
    
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
    
    
    
    
<%# form_tag("create", method: "post") do %>
  <%#= text_field 'comment', 'comment_title' %>
  <%#= text_field 'comment', 'body' %>

  <%#= submit_tag 'Add Comment' %>

  <%#= hidden_field 'commentable', 'commentable', :value => @model.type %>
  <%#= hidden_field 'commentable', 'commentable_id', :value => @model.id %>
<%# end %>

MOOC_blog/app/views/comments/_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Lecture</th>
      <th>Comment title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_id %></td>
        <td><%= comment.lecture_id %></td>
        <td><%= comment.comment_title %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

MOOC_blog/app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

MOOC_blog/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', :back%>

MOOC_blog/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', lecture_path(:id=>@comment.lecture_id) %>

MOOC_blog/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Lecture:</strong>
  <%= @comment.lecture_id %>
</p>

<p>
  <strong>Comment title:</strong>
  <%= @comment.comment_title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit Comment', edit_comment_path(@comment) %> |
<%= link_to 'Back to lecture', lecture_path(:id=>@comment.lecture_id) %>