MOOC_blog/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :lectures do
    resources :comments
  end
  resources :courses do
    resources :lectures
  end
  get 'pages/index'

  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'comments/create'

  mount Ckeditor::Engine => '/ckeditor'
  

  devise_for :users, controllers: {sessions: 'users/sessions',registrations: "users/registrations"}

  resources :users
  resources :courses
  resources :comments, :only => [:create, :destroy]
  resources :lectures do
    member do
      put 'like' => 'lectures#upvote'
      put 'unlike' => 'lectures#downvote'
    end
  end
  
  get 'lectures/index'

  get 'lectures/show'

  get 'lectures/edit'

  get 'lectures/create'

  get 'lectures/destroy'

  get 'lectures/new'

  get 'lectures/update'

  get 'lectures/set_lecture'

  get 'lectures/lecture_params'

 

  get 'courses/index'
  get 'courses/new'
  get 'courses/create'
  get 'courses/show'
  get 'courses/update'
  get 'courses/create'
  get 'courses/create'
  
  

  root 'courses#index'

end

MOOC_blog/app/models/lecture.rb
class Lecture < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
	mount_uploader :image, ImageUploader 
  belongs_to :course
	belongs_to :user
  has_many :comments ,:dependent=>:delete_all # , :as=>:recipient
#  has_many :upload_files
  
	acts_as_votable
#	acts_as_commentable
end

MOOC_blog/app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
skip_before_action :verify_authenticity_token
before_action :set_lecture, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  def index

    @lectures = Lecture.all.order(:created_at => 'asc')
  end
  def list
    @course = Course.find(params[:course_id])
    @lectures = @course.lectures
#  @lectures = Lecture.all.order(:cached_votes_up => 'desc')
  end

  def show
    @comments = @lecture.comments.all    
  end

  def edit
    @courses = Course.all
  end

  def create
    @lecture = Lecture.new(lecture_params)

    respond_to do |format|
      if @lecture.save
        format.html { redirect_to @lecture }
        format.json { render :show, status: :created, location: @lecture }
      else
        format.html { render :new }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @lecture.destroy
    respond_to do |format|
      format.html { redirect_to lectures_url }
      format.json { head :no_content }
    end
  end

  def new
    @course_id= params[:lecture_id];
    @lecture = Lecture.new
  end

  def update
    respond_to do |format|
      if @lecture.update(lecture_params)
        format.html { redirect_to @lecture }
        format.json { render :show, status: :ok, location: @lecture }
      else
        format.html { render :edit }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  #upvote from user
  #down vote from user
  def upvote
    @lecture.upvote_from current_user
    redirect_to lecture_path
  end

  def downvote
    @lecture.downvote_from current_user
    redirect_to lecture_path
  end
private
  def set_lecture
    @lecture = Lecture.find(params[:id])
  end

  def lecture_params
    params.require(:lecture).permit(:title, :content, :image, :attachment, :id, :course_id, :user_id)
  end
end

MOOC_blog/app/helpers/lectures_helper.rb
module LecturesHelper
end

MOOC_blog/app/views/lectures/_form.html.erb
<div class = "well">
<%= form_for(@lecture) do |f| %>
  <% if @lecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
      <% @lecture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :course_id, :value =>course_id %>
  <%= f.hidden_field :user_id, :value =>current_user.id %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.cktext_area :content, :input_html => { :value => "Default value" } %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
      <div class="field">
    <%= f.label :attachment %><br>
    <%= f.file_field :attachment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

MOOC_blog/app/views/lectures/create.html.erb
<h1>Lectures#create</h1>
<p>Find me in app/views/lectures/create.html.erb</p>

MOOC_blog/app/views/lectures/destroy.html.erb
<h1>Lectures#destroy</h1>
<p>Find me in app/views/lectures/destroy.html.erb</p>

MOOC_blog/app/views/lectures/edit.html.erb
<h1>Editing Lecture</h1>

<%= render 'form' , :course_id => @lecture.course_id %>

<%= link_to 'Show', @lecture %> |
<%= link_to 'Back', lectures_path %>

MOOC_blog/app/views/lectures/index.html.erb
<p id="notice"><%= notice %></p>
<p id="notice"><%= notice %></p>

<h1>All Lectures</h1>
<% @lectures.each do |lecture| %>
<div class = "blog well">
  <%= image_tag lecture.image ,:size=>"125x125" ,class:"pull-right" %>
  <h2 style="color: darkcyan"><%= lecture.title %></h2>

  <p style="font-size: 24px;"> <%= raw(lecture.content)%></p>
  <div style="height: 10px;"></div>
  <%= link_to 'Show more >>', lecture %>
  
</div>
<% end %>

MOOC_blog/app/views/lectures/lecture_params.html.erb
<h1>Lectures#lecture_params</h1>
<p>Find me in app/views/lectures/lecture_params.html.erb</p>

MOOC_blog/app/views/lectures/list.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lectures</h1>
<% @lectures.each do |lecture| %>
<div class = "blog well">
  <%= image_tag lecture.image ,:size=>"150x150" ,class:"pull-right" %>
  <h1><%= lecture.title %></h1>

  <%= raw(lecture.content) %>
  <div style="height: 10px;"></div>
  <%= link_to 'Show more >>', lecture %>
  <% if current_user && current_user.id = @lecture.user_id %>
  <%= link_to 'Edit', edit_lecture_path(lecture) %>
  <%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>
<% end %>

MOOC_blog/app/views/lectures/new.html.erb
<% if params[:course_id] %>
<h1>New Lecture</h1>

<%= render 'form', :course_id => params[:course_id] %>

<%= link_to 'Back', course_path(:id=>params[:course_id]), class:"btn btn-info"%>

<% end %>
<div style="height: 50px;"></div>

MOOC_blog/app/views/lectures/set_lecture.html.erb
<h1>Lectures#set_lecture</h1>
<p>Find me in app/views/lectures/set_lecture.html.erb</p>

MOOC_blog/app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>

<div class = "blog well text-centered">
  <%= image_tag @lecture.image ,:size=>"150x150" ,class:"pull-right" %>
  <strong style="font-size: 16px; color: darkcyan">Title:</strong>
  <p style="font-size: 18px;"><%= @lecture.title %></p><br>
   <strong style="font-size: 20px; color: darkcyan">Content:</strong>
   <p style="font-size: 18px;"><%= raw(@lecture.content) %></p>
  <strong style="font-size: 20px; color: darkcyan">Download Link:   </strong>
  <a href="<%= @lecture.attachment_url%>" download><%= @lecture.attachment%></a>
  <%#= link_to "Download File", @lecture.attachment_url. %>
  <br><br>
    like
<%= link_to like_lecture_path(@lecture), class: "like",method: :put do %>
<button type="button" class="btn btn-info" aria-label="Left Align">
    <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center" aria-hidden="true"></span>
    <span class="badge"><%= @lecture.get_upvotes.size%></span>
</button>
<% end %>

unlike
<%= link_to unlike_lecture_path(@lecture), class: "unlike",method: :put do %>
<button type="button" class="btn btn-danger" aria-label="Left Align">
    <span class="glyphicon glyphicon-thumbs-down glyphicon-align-center" aria-hidden="true"></span>
    <span class="badge"><%= @lecture.get_downvotes.size%></span>
</button>
<%#*if 5 user dislike the lecture it is considered as spam%>
  <% if @lecture.get_downvotes.size == 5 %>
    <% Lecture.destroy(@lecture.id) %>
  <% end %>
<% end %>
</div>
<br><hr> 

<div class="row">
   <div class = "blog well">
<%#= render 'comments/comment_form' %>
      <h2>Comments</h2>
      <div id="comments">
       <%=  render @lecture.comments %>
      </div>
   </div>
    <div class = "blog well">
    <% if current_user %>
    <div class="row">
    <%= form_for [@lecture,Comment.new] do |f|%>
    <div class="form-group col-md-9 col-md-offset-2">
      <%=f.label :comment_title,"title",class:"text-center" %>
      <%= f.text_field :comment_title ,class:"form-control" %>
    </div>
        <div class="col-md-offset-1 col-md-1">
          <%=image_tag current_user.profile_picture,width:45,height:45 %>
        </div>
    <div class="form-group col-md-7">
      <%=f.label :body,"Add comment",class:"text-center" %>
      <%= f.text_area :body, as: :text, input_html: {rows: "5"}, class:"form-control" %>
    </div>
    <%= f.hidden_field :lecture_id, :value => @lecture.id %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :course_id, :value => @lecture.course_id %>
    </div>
    <div class="row">
      <div class="col-md-offset-2 form-group">
        <%= f.submit "Add Comment", class:"btn btn-info" %>
      </div>
    </div>
    <% end %>
    <% else %>
    <div class="alert alert-warning">
      <strong>Warning!</strong> Login to add your comment.
    </div>
    <% end %>    
</div>

<div class="col-md-offset-2">
<% if current_user && current_user.id == @lecture.user_id %>
  <%= link_to 'Edit', edit_lecture_path(@lecture) ,class:"btn btn-warning"%> 
  <%= link_to 'Destroy', @lecture, method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-danger"%> 
<% end %>
<%= link_to 'Back', course_path(:id=>@lecture.course_id),class:"btn btn-info"%>
</div>
</div>
<div style="height: 50px;"></div>

MOOC_blog/app/views/lectures/update.html.erb
<h1>Lectures#update</h1>
<p>Find me in app/views/lectures/update.html.erb</p>