MOOC_blog/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :lectures do
    resources :comments
  end
  resources :courses do
    resources :lectures
  end
  get 'pages/index'

  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'comments/create'

  mount Ckeditor::Engine => '/ckeditor'
  

  devise_for :users, controllers: {sessions: 'users/sessions',registrations: "users/registrations"}

  resources :users
  resources :courses
  resources :comments, :only => [:create, :destroy]
  resources :lectures do
    member do
      put 'like' => 'lectures#upvote'
      put 'unlike' => 'lectures#downvote'
    end
  end
  
  get 'lectures/index'

  get 'lectures/show'

  get 'lectures/edit'

  get 'lectures/create'

  get 'lectures/destroy'

  get 'lectures/new'

  get 'lectures/update'

  get 'lectures/set_lecture'

  get 'lectures/lecture_params'

 

  get 'courses/index'
  get 'courses/new'
  get 'courses/create'
  get 'courses/show'
  get 'courses/update'
  get 'courses/create'
  get 'courses/create'
  
  

  root 'courses#index'

end

MOOC_blog/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
   before_action :authenticate_user!, only: [:new, :create , :edit, :update, :destroy]
   before_action :set_course, only: [:show, :edit, :update, :destroy]
  
   def index
      @course = Course.all
   end
   
   def new
      @course = Course.new
   end
   
   def create
      @course = Course.new(course_params)
      respond_to do |format|
         if @course.save
            format.html {redirect_to @course}
         else
            format.html {reder :new}
         end
      end
   end
   
   def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course }
      else
        format.html { render :edit }
      end
    end
   end
   
   def edit
   end
   
   def show
   end
   
   def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url}
    end
   end
   
 private  
   def set_course
      @course = Course.find(params[:id])
   end
   
   def course_params
      params.require(:course).permit(:course_title,:image,:user_id)
   end
   
end

MOOC_blog/app/helpers/courses_helper.rb
module CoursesHelper
end

MOOC_blog/app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course_title %><br>
    <%= f.text_field :course_title %>
    <%= f.file_field :image %><br />
    <%= f.hidden_field :user_id, :value =>current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MOOC_blog/app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course,class:"btn btn-info" %> 
<%= link_to 'Back', courses_path,class:"btn btn-info" %>
<br>

MOOC_blog/app/views/courses/index.html.erb
<style >
  body{
    background-image: url("/assets/images/Books-laptop-smartphone-uhd-wallpapers1.jpg");
    background-size: cover; 
    background-repeat: no-repeat;
    font-size : 24px;
  }
  #trans{
  background-color: rgba(255,255,255,0.7);
  font-size : 24px;
  }
  h1{
    color: orange;
  }
</style>
<div id="trans" style="padding: 20px;">
<h1>Top Courses</h1><br />
<% @course.each{|k| puts k.course_title}%>
<div class="table-responsive">
    <table  class="table table-hover ">
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th>Author</th>
      <th>Show Content</th>
    </tr>
  </thead>

  <tbody>
    <% @course.each do |course| %>
      <tr style="font-size : 24px;">
          <td><p  style="font-size : 24px;"><%= raw(course.course_title) %></p></td>
          <td><p  style="font-size : 24px;"><%= image_tag course.image ,:size=>"70x70" %></p></td>
          <td><p  style="font-size : 24px;"><%= raw(User.find(course.user_id).name) %></p></td>
          <td><p  style="font-size : 24px;"><%= link_to 'Show', course ,class:"btn btn-info" %></p></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<% if current_user && current_user.user_type == "instructor" %>
<%= link_to 'New Course', new_course_path ,class:"btn btn-info" %>
<% end %>
<div style="height:50px;"></div>
</div>
</div>

MOOC_blog/app/views/courses/new.html.erb
<h>New Course</h>

<%= render 'form' %>
<%= link_to 'Back', courses_path ,class:"btn btn-info", class:"btn btn-info"  %>

MOOC_blog/app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>
<p class="text-center" style="font-size: 24px; padding :20px;">
  <strong>Course Title:</strong>
  <%= raw(@course.course_title) %><br><br>
  <%= image_tag @course.image %>
  </p>
  
  <strong style="font-size: 24px; color: brown;">Lectures: </strong>
  <% @course.lectures.each do |lecture| %>
        <div class = "blog well">
            <h1 style="color: blueviolet;"><%= lecture.title %></h1>
          <%= raw(lecture.content) %>
          <div style="height: 10px;"></div>
          <%= link_to 'Show more >>', lecture_path(lecture) %>
        </div>
  <% end %>

<br>

<%= link_to 'Back', courses_path,class:"btn btn-success"  %>
<% if current_user && current_user.id == @course.user_id %>
<%= link_to 'Edit', edit_course_path(@course),class:"btn btn-warning" %> 
<%= link_to 'Destroy', @course, method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-danger"%>
<% end %>
<% if current_user && current_user.user_type == "instructor" %>
  <%= link_to 'Add Lecture', new_lecture_path(:course_id =>@course.id) ,class:"btn btn-info "%>
<% end %>
<br> <br> <br>